FROM node:18

RUN mkdir /app
WORKDIR /app

RUN apt-get update && apt-get upgrade -y

COPY . /app
RUN npm install
RUN npm run build

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

CMD [ "node", ".output/server/index.mjs" ]
